---
- name: Setting Up Redis-DB Server
  hosts: redis
  become: yes
  tasks:
  - name: Installing Redis Repo File
    ansible.builtin.yum: 
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: present