---
- name: Setting Up user Server For Roboshop Project
  hosts: user
  become: yes
  tasks:
  - name: Setup NodeJS Repo
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: Installing NodeJS
    ansible.builtin.yum:
      name: nodejs 
      state: installed

  - name: Checking System User
    ansible.builtin.shell: id roboshop
    register: out
    ignore_errors: yes

  - name: Creating System User
    ansible.builtin.user:
      name: roboshop
    when: out.rc != 0

  - name: Creating app Directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Downloading Application Code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp/user.zip

  - name: Unarchive user.zip file
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: Installing Dependencies
    ansible.builtin.shell: npm install
    args:
      chdir: /app

  - name: Copying user.service file
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: load Systemd service
    ansible.builtin.systemd_service:
      name: user.service
      state: reloaded
    ignore_errors: yes

  - name: enable and starting user service
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes

  - name: Copying mongo.repo file
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installing mongodb client
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: loading schema
    ansible.builtin.shell: mongo --host mongodb.cloudevops.cloud < /app/schema/user.js

  - name: Re-starting user service
    ansible.builtin.service:
      name: user
      state: restarted
  
