---
- name: Setting Up MySQL Server
  hosts: mysql
  become: yes
  tasks:
  - name: Disable Existing Mysql
    ansible.builtin.shell: yum module disable mysql -y 

  - name: Copying mysql.repo file
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: Install MySQL
    ansible.builtin.yum:
      name: mysql-community-server
      state: installed

  - name: Enabling and Starting mysqld service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: change the default root password
    ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

  
    